version: '3'
services:
  sveltekit:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: sh -c "yarn install && yarn dev --host"
    ports:
      - '5173:5173'
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
    env_file:
      - .env
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: database
    # volumes:
    #   - ./data/postgres:/var/lib/postgresql/data

volumes:
  node_modules:
